#8-1 PROGRAMMING EXERCISES
#WRITE A PROGRAM THAT GETS A STRING CONTAINING A PERSON'S
#FIRST, MIDDLE, AND LAST NAMES, AND DISPLAYS THEIR FIRST, MIDDLE, 
#AND LAST INITIALS. FOR EXAMPLE, IF THE USER ENTER JOHN WILLIAM SMITH,
#THE PROGRAM SHOULD DISPLAY J.W.S

def get_initials():
    #GET USER INPUT
    name = input("PLEASE ENTER FULL NAME: ")

    # SPLIT NAME IN ORDER TO GET FIRST INITIAL 
    words = name.split()#EXAMPLE: ['MARY JANE' BECOMES 'MARY', 'JANE']
    
    # GET FIRST LETTER OF NAME AND UPPERCASE
    initials = "" #INITIALIZE EMPTY STRING TO COLLECT FIRST LETTER
    for word in words: #LOOP THROUGH EACH ELEMENT
        #APPEND UPPERCASE INITIAL TO INITIALS STRING
        initials += word[0].upper() + '.' #INITIALS= INITIALS + WORD[0] + '.'
    
    # DISPLAY INITIALS
    print(initials)

# RUN
get_initials()