#8-10 PROGRAMMING EXERCISE
#WRITE A PROGRAM THAT ALLOWS A USER TO ENTER A STRING AND DISPLAYS
#THE CHARACTER THAT APPEARS MOST FREQUENTLY IN THE STRING

def main():
  user_string = input("PLEASE ENTER A STRING OF CHARACTERS:)
  alphabet = ['ABCDEFGHIJKLMNOPQRSTUVWXYZ']
  characters = alphabet.split()
  print("THE MOST FREQUENT CHARACTER", )

def character_count():

