#8-9 PROGRAMMING EXERCISE
#WRITE A PROGRAM WITH A FUNCTION THAT ACCEPTS A STRING AS AN ARGUMENT AND RETURNS THE NUMBER OF VOWELS
#THE STRING CONTAINS. THE APPLICATION SHOULD HAVE ANOTHER FUNCTION THAT ACCEPTS A STRING AS AN ARGUMENT AND RETURNS
#THE NUMBER OF CONSONANTS THAT THE STRING CONTAINS. DISPLAY OUTCOME

def num_consonants(s):
  vowels = ['a', 'e', 'i', 'o', 'u']#CREATE VOWEL 
  c_count = 0

#COUNT CONSONANTS 
for ch in s:
  if ch.isaplha() and ch.lower() not in vowels:
    c_count +=1
#RETURN THE CONSONANT COUNT
return c_count
